pages:
  - name: ホーム - 未来
    path: /2024-04-28
  - name: ホーム - 現在
    path: /
  - name: ホーム - 過去
    path: /2024-04-02
  - name: 出走表
    path: /races/de53571b-24c4-4de8-85c8-a3e2ef6b6d47/race-card
  - name: オッズ - 締め切り前
    path: /races/de53571b-24c4-4de8-85c8-a3e2ef6b6d47/odds
  - name: オッズ - 締め切り後
    path: /races/d5a7db89-0cb2-4292-965b-b9f76bf8aca5/odds
  - name: 結果
    path: /races/d5a7db89-0cb2-4292-965b-b9f76bf8aca5/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720
